### ISSUE TITLE
Tracking: migrate to SJTUTeX v2

### ISSUE THREAD

**Issue by skyzh** [sjtug/SJTUThesis#761]
- [x] https://github.com/sjtug/SJTUThesis/pull/759
- [x] add cover and copyright page
- [x] fix example compile
- [ ] update readme and deprecate v1

**Comment by PaleNeutron** [comment]
[main.log](https://github.com/sjtug/SJTUThesis/files/8103438/main.log)
Mac环境下编译citation失败

**Comment by skyzh** [comment]
> [main.log](https://github.com/sjtug/SJTUThesis/files/8103438/main.log)
> Mac环境下编译citation失败

Hi, 如果有使用上的问题，可以先按 readme 的流程自查一遍，不要在无关的 issue 下发布信息。Thanks!
